### ISSUE TITLE
Story: View paginated list of posts

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Django-Blog#1]
As a **site user** I can **View paginated list of posts** so that **I can select which post i want to view.**

## Acceptance Criteria:
-  "Given more than one post in the database, these multiple posts are listed."

- "When a user opens the main page a list of posts is seen."

- "Then the user sees all post titles with pagination to choose what to read."

## Tasks to perform:
- [ ] Link to information provided by data base
- [ ] Add functions to display correctly on page
- [ ] Push out put to view.
